version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_started
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/home/node/app
      - ignore_api:/home/node/app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/home/node/app
      - ignore_client:/home/node/app/node_modules



volumes:
  ignore_api:
  ignore_client:
  mongodb_data: